#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaLockedStyleNotification

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaLockedStyleNotification.AthenaLockedStyleNotification_C
// 0x0010 (0x0240 - 0x0230)
class UAthenaLockedStyleNotification_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0230(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCommonTextBlock*                       DescriptionText;                                   // 0x0238(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_AthenaLockedStyleNotification(int32 EntryPoint);
	void Construct();
	void SetLockedStyleDescription(const class FText& LockedStyleDescription);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AthenaLockedStyleNotification_C">();
	}
	static class UAthenaLockedStyleNotification_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaLockedStyleNotification_C>();
	}
};
static_assert(alignof(UAthenaLockedStyleNotification_C) == 0x000008, "Wrong alignment on UAthenaLockedStyleNotification_C");
static_assert(sizeof(UAthenaLockedStyleNotification_C) == 0x000240, "Wrong size on UAthenaLockedStyleNotification_C");
static_assert(offsetof(UAthenaLockedStyleNotification_C, UberGraphFrame) == 0x000230, "Member 'UAthenaLockedStyleNotification_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UAthenaLockedStyleNotification_C, DescriptionText) == 0x000238, "Member 'UAthenaLockedStyleNotification_C::DescriptionText' has a wrong offset!");

}

