#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Athena_Fly

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Athena_Fly.GA_Athena_Fly_C
// 0x0008 (0x0940 - 0x0938)
class UGA_Athena_Fly_C final : public UFortGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0938(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_Athena_Fly(int32 EntryPoint);
	void Added_3EAC858E4A7943CBB81C86992D3F3CC1();
	void K2_ActivateAbility();
	void Removed_AAD5AA1645BDC2889C719BBCB8694960();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Athena_Fly_C">();
	}
	static class UGA_Athena_Fly_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Athena_Fly_C>();
	}
};
static_assert(alignof(UGA_Athena_Fly_C) == 0x000008, "Wrong alignment on UGA_Athena_Fly_C");
static_assert(sizeof(UGA_Athena_Fly_C) == 0x000940, "Wrong size on UGA_Athena_Fly_C");
static_assert(offsetof(UGA_Athena_Fly_C, UberGraphFrame) == 0x000938, "Member 'UGA_Athena_Fly_C::UberGraphFrame' has a wrong offset!");

}

