#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCNS_Durrrables_Health

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCNS_Durrrables_Health.GCNS_Durrrables_Health_C
// 0x0000 (0x0080 - 0x0080)
class UGCNS_Durrrables_Health_C final : public UFortGameplayCueNotify_Simple
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCNS_Durrrables_Health_C">();
	}
	static class UGCNS_Durrrables_Health_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCNS_Durrrables_Health_C>();
	}
};
static_assert(alignof(UGCNS_Durrrables_Health_C) == 0x000008, "Wrong alignment on UGCNS_Durrrables_Health_C");
static_assert(sizeof(UGCNS_Durrrables_Health_C) == 0x000080, "Wrong size on UGCNS_Durrrables_Health_C");

}

