#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemReceivedDeepFreezeBundleHeader

#include "Basic.hpp"


namespace SDK::Params
{

// Function ItemReceivedDeepFreezeBundleHeader.ItemReceivedDeepFreezeBundleHeader_C.ExecuteUbergraph_ItemReceivedDeepFreezeBundleHeader
// 0x0010 (0x0010 - 0x0000)
struct ItemReceivedDeepFreezeBundleHeader_C_ExecuteUbergraph_ItemReceivedDeepFreezeBundleHeader final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButton*                          K2Node_ComponentBoundEvent_Button;                 // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ItemReceivedDeepFreezeBundleHeader_C_ExecuteUbergraph_ItemReceivedDeepFreezeBundleHeader) == 0x000008, "Wrong alignment on ItemReceivedDeepFreezeBundleHeader_C_ExecuteUbergraph_ItemReceivedDeepFreezeBundleHeader");
static_assert(sizeof(ItemReceivedDeepFreezeBundleHeader_C_ExecuteUbergraph_ItemReceivedDeepFreezeBundleHeader) == 0x000010, "Wrong size on ItemReceivedDeepFreezeBundleHeader_C_ExecuteUbergraph_ItemReceivedDeepFreezeBundleHeader");
static_assert(offsetof(ItemReceivedDeepFreezeBundleHeader_C_ExecuteUbergraph_ItemReceivedDeepFreezeBundleHeader, EntryPoint) == 0x000000, "Member 'ItemReceivedDeepFreezeBundleHeader_C_ExecuteUbergraph_ItemReceivedDeepFreezeBundleHeader::EntryPoint' has a wrong offset!");
static_assert(offsetof(ItemReceivedDeepFreezeBundleHeader_C_ExecuteUbergraph_ItemReceivedDeepFreezeBundleHeader, K2Node_ComponentBoundEvent_Button) == 0x000008, "Member 'ItemReceivedDeepFreezeBundleHeader_C_ExecuteUbergraph_ItemReceivedDeepFreezeBundleHeader::K2Node_ComponentBoundEvent_Button' has a wrong offset!");

// Function ItemReceivedDeepFreezeBundleHeader.ItemReceivedDeepFreezeBundleHeader_C.BndEvt__CandleLightButton_K2Node_ComponentBoundEvent_61_CommonButtonClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct ItemReceivedDeepFreezeBundleHeader_C_BndEvt__CandleLightButton_K2Node_ComponentBoundEvent_61_CommonButtonClicked__DelegateSignature final
{
public:
	class UCommonButton*                          Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ItemReceivedDeepFreezeBundleHeader_C_BndEvt__CandleLightButton_K2Node_ComponentBoundEvent_61_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on ItemReceivedDeepFreezeBundleHeader_C_BndEvt__CandleLightButton_K2Node_ComponentBoundEvent_61_CommonButtonClicked__DelegateSignature");
static_assert(sizeof(ItemReceivedDeepFreezeBundleHeader_C_BndEvt__CandleLightButton_K2Node_ComponentBoundEvent_61_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong size on ItemReceivedDeepFreezeBundleHeader_C_BndEvt__CandleLightButton_K2Node_ComponentBoundEvent_61_CommonButtonClicked__DelegateSignature");
static_assert(offsetof(ItemReceivedDeepFreezeBundleHeader_C_BndEvt__CandleLightButton_K2Node_ComponentBoundEvent_61_CommonButtonClicked__DelegateSignature, Button) == 0x000000, "Member 'ItemReceivedDeepFreezeBundleHeader_C_BndEvt__CandleLightButton_K2Node_ComponentBoundEvent_61_CommonButtonClicked__DelegateSignature::Button' has a wrong offset!");

}

