#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RewardOrVerticalWidget

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass RewardOrVerticalWidget.RewardOrVerticalWidget_C
// 0x0000 (0x0B50 - 0x0B50)
class URewardOrVerticalWidget_C final : public UFortRewardInfoButton
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"RewardOrVerticalWidget_C">();
	}
	static class URewardOrVerticalWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URewardOrVerticalWidget_C>();
	}
};
static_assert(alignof(URewardOrVerticalWidget_C) == 0x000008, "Wrong alignment on URewardOrVerticalWidget_C");
static_assert(sizeof(URewardOrVerticalWidget_C) == 0x000B50, "Wrong size on URewardOrVerticalWidget_C");

}

