#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShowdownPin

#include "Basic.hpp"

#include "FortniteUI_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function ShowdownPin.ShowdownPin_C.ExecuteUbergraph_ShowdownPin
// 0x0180 (0x0180 - 0x0000)
struct ShowdownPin_C_ExecuteUbergraph_ShowdownPin final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetTournamentPinUnlockScore_ReturnValue;  // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable1;                               // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable1;                                // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable2;                               // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable2;                                // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable3;                                // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable3;                               // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_float_Variable;                               // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     Temp_object_Variable;                              // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     Temp_object_Variable1;                             // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     Temp_object_Variable2;                             // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     Temp_object_Variable3;                             // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51[0x3];                                       // 0x0051(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_CustomEvent_Score;                          // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue1;             // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable4;                                // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue;              // 0x0064(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_65[0x3];                                       // 0x0065(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0068(0x0018)()
	int32                                         K2Node_Select_Default;                             // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue1;             // 0x0084(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue2;             // 0x0085(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_86[0x2];                                       // 0x0086(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_Select1_Default;                            // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Select2_Default;                            // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     K2Node_Select3_Default;                            // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_Points;                         // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9C[0x4];                                       // 0x009C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x00A0(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x00E0(0x0010)(ZeroConstructor, ReferenceParm)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F1[0x7];                                       // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00F8(0x0018)()
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_MakeColor_ReturnValue;                    // 0x0118(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable1;                               // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_129[0x7];                                      // 0x0129(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue1;          // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable4;                               // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select4_Default;                            // 0x0139(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_13A[0x2];                                      // 0x013A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable5;                                // 0x013C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue;               // 0x0140(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetStartTime_ReturnValue;                 // 0x0144(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_PauseAnimation_ReturnValue1;              // 0x0148(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x014C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_14D[0x3];                                      // 0x014D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x0150(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_154[0x4];                                      // 0x0154(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0158(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetEndTime_ReturnValue;                   // 0x0160(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable6;                                // 0x0164(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x0168(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select5_Default;                            // 0x016C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue1;               // 0x0170(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable5;                               // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_179[0x3];                                      // 0x0179(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_Select6_Default;                            // 0x017C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin) == 0x000008, "Wrong alignment on ShowdownPin_C_ExecuteUbergraph_ShowdownPin");
static_assert(sizeof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin) == 0x000180, "Wrong size on ShowdownPin_C_ExecuteUbergraph_ShowdownPin");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, EntryPoint) == 0x000000, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::EntryPoint' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, CallFunc_GetTournamentPinUnlockScore_ReturnValue) == 0x000004, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::CallFunc_GetTournamentPinUnlockScore_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, Temp_bool_Variable) == 0x000008, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, CallFunc_Conv_IntToFloat_ReturnValue) == 0x00000C, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, Temp_int_Variable) == 0x000010, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, Temp_bool_Variable1) == 0x000014, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::Temp_bool_Variable1' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, Temp_int_Variable1) == 0x000018, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::Temp_int_Variable1' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, Temp_bool_Variable2) == 0x00001C, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::Temp_bool_Variable2' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, Temp_int_Variable2) == 0x000020, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::Temp_int_Variable2' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, Temp_int_Variable3) == 0x000024, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::Temp_int_Variable3' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, Temp_bool_Variable3) == 0x000028, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::Temp_bool_Variable3' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, Temp_float_Variable) == 0x00002C, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, Temp_object_Variable) == 0x000030, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, Temp_object_Variable1) == 0x000038, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::Temp_object_Variable1' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, Temp_object_Variable2) == 0x000040, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::Temp_object_Variable2' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, Temp_object_Variable3) == 0x000048, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::Temp_object_Variable3' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, K2Node_Event_IsDesignTime) == 0x000050, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, K2Node_CustomEvent_Score) == 0x000054, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::K2Node_CustomEvent_Score' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, CallFunc_Conv_IntToFloat_ReturnValue1) == 0x000058, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::CallFunc_Conv_IntToFloat_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, Temp_int_Variable4) == 0x00005C, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::Temp_int_Variable4' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, CallFunc_Divide_FloatFloat_ReturnValue) == 0x000060, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, CallFunc_Less_FloatFloat_ReturnValue) == 0x000064, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::CallFunc_Less_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, CallFunc_Conv_IntToText_ReturnValue) == 0x000068, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, K2Node_Select_Default) == 0x000080, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, CallFunc_Less_FloatFloat_ReturnValue1) == 0x000084, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::CallFunc_Less_FloatFloat_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, CallFunc_Less_FloatFloat_ReturnValue2) == 0x000085, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::CallFunc_Less_FloatFloat_ReturnValue2' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, K2Node_Select1_Default) == 0x000088, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::K2Node_Select1_Default' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, K2Node_Select2_Default) == 0x00008C, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::K2Node_Select2_Default' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, K2Node_Select3_Default) == 0x000090, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::K2Node_Select3_Default' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, K2Node_CustomEvent_Points) == 0x000098, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::K2Node_CustomEvent_Points' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, K2Node_MakeStruct_FormatArgumentData) == 0x0000A0, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, K2Node_MakeArray_Array) == 0x0000E0, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, Temp_byte_Variable) == 0x0000F0, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, CallFunc_Format_ReturnValue) == 0x0000F8, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, CallFunc_GetDynamicMaterial_ReturnValue) == 0x000110, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, CallFunc_MakeColor_ReturnValue) == 0x000118, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::CallFunc_MakeColor_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, Temp_byte_Variable1) == 0x000128, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::Temp_byte_Variable1' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, CallFunc_GetDynamicMaterial_ReturnValue1) == 0x000130, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::CallFunc_GetDynamicMaterial_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, Temp_bool_Variable4) == 0x000138, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::Temp_bool_Variable4' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, K2Node_Select4_Default) == 0x000139, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::K2Node_Select4_Default' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, Temp_int_Variable5) == 0x00013C, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::Temp_int_Variable5' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, CallFunc_PauseAnimation_ReturnValue) == 0x000140, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::CallFunc_PauseAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, CallFunc_GetStartTime_ReturnValue) == 0x000144, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::CallFunc_GetStartTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, CallFunc_PauseAnimation_ReturnValue1) == 0x000148, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::CallFunc_PauseAnimation_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x00014C, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, CallFunc_Add_FloatFloat_ReturnValue) == 0x000150, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, CallFunc_PlayAnimation_ReturnValue) == 0x000158, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, CallFunc_GetEndTime_ReturnValue) == 0x000160, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::CallFunc_GetEndTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, Temp_int_Variable6) == 0x000164, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::Temp_int_Variable6' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x000168, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, K2Node_Select5_Default) == 0x00016C, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::K2Node_Select5_Default' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, CallFunc_PlayAnimation_ReturnValue1) == 0x000170, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::CallFunc_PlayAnimation_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, Temp_bool_Variable5) == 0x000178, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::Temp_bool_Variable5' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_ExecuteUbergraph_ShowdownPin, K2Node_Select6_Default) == 0x00017C, "Member 'ShowdownPin_C_ExecuteUbergraph_ShowdownPin::K2Node_Select6_Default' has a wrong offset!");

// Function ShowdownPin.ShowdownPin_C.EventFixPts
// 0x0004 (0x0004 - 0x0000)
struct ShowdownPin_C_EventFixPts final
{
public:
	int32                                         Points;                                            // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ShowdownPin_C_EventFixPts) == 0x000004, "Wrong alignment on ShowdownPin_C_EventFixPts");
static_assert(sizeof(ShowdownPin_C_EventFixPts) == 0x000004, "Wrong size on ShowdownPin_C_EventFixPts");
static_assert(offsetof(ShowdownPin_C_EventFixPts, Points) == 0x000000, "Member 'ShowdownPin_C_EventFixPts::Points' has a wrong offset!");

// Function ShowdownPin.ShowdownPin_C.EventSetTier
// 0x0004 (0x0004 - 0x0000)
struct ShowdownPin_C_EventSetTier final
{
public:
	int32                                         Score;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ShowdownPin_C_EventSetTier) == 0x000004, "Wrong alignment on ShowdownPin_C_EventSetTier");
static_assert(sizeof(ShowdownPin_C_EventSetTier) == 0x000004, "Wrong size on ShowdownPin_C_EventSetTier");
static_assert(offsetof(ShowdownPin_C_EventSetTier, Score) == 0x000000, "Member 'ShowdownPin_C_EventSetTier::Score' has a wrong offset!");

// Function ShowdownPin.ShowdownPin_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct ShowdownPin_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ShowdownPin_C_PreConstruct) == 0x000001, "Wrong alignment on ShowdownPin_C_PreConstruct");
static_assert(sizeof(ShowdownPin_C_PreConstruct) == 0x000001, "Wrong size on ShowdownPin_C_PreConstruct");
static_assert(offsetof(ShowdownPin_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'ShowdownPin_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function ShowdownPin.ShowdownPin_C.Refresh
// 0x01A0 (0x01A0 - 0x0000)
struct ShowdownPin_C_Refresh final
{
public:
	EFortShowdownPinState                         PinState;                                          // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortShowdownEventState                       Temp_byte_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable1;                                // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable2;                                // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable3;                                // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable4;                                // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable5;                                // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable6;                                // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortShowdownEventState                       Temp_byte_Variable1;                               // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x0028(0x0018)()
	class FText                                   Temp_text_Variable1;                               // 0x0040(0x0018)()
	class FText                                   Temp_text_Variable2;                               // 0x0058(0x0018)()
	class FText                                   Temp_text_Variable3;                               // 0x0070(0x0018)()
	class FText                                   Temp_text_Variable4;                               // 0x0088(0x0018)()
	class FText                                   Temp_text_Variable5;                               // 0x00A0(0x0018)()
	class FText                                   Temp_text_Variable6;                               // 0x00B8(0x0018)()
	bool                                          Temp_bool_Variable;                                // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable1;                               // 0x00D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EFortShowdownPinState                         Temp_byte_Variable2;                               // 0x00D2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable2;                               // 0x00D3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EFortShowdownPinState                         Temp_byte_Variable3;                               // 0x00D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D5[0x3];                                       // 0x00D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetBestEventScore_ReturnValue;            // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetCurrentEventScore_ReturnValue;         // 0x00DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortShowdownEventState                       CallFunc_GetEventState_ReturnValue;                // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortShowdownEventState                       CallFunc_GetEventState_ReturnValue1;               // 0x00E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E2[0x2];                                       // 0x00E2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_Select_Default;                             // 0x00E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetBestEventScore_ReturnValue1;           // 0x00E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x00F0(0x0018)()
	int32                                         CallFunc_GetCurrentEventScore_ReturnValue1;        // 0x0108(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_10C[0x4];                                      // 0x010C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue1;              // 0x0110(0x0018)()
	class FText                                   K2Node_Select1_Default;                            // 0x0128(0x0018)()
	int32                                         CallFunc_GetTournamentBestScore_ReturnValue;       // 0x0140(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue1;             // 0x0144(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select2_Default;                            // 0x0148(0x0004)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14C[0x4];                                      // 0x014C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue2;              // 0x0150(0x0018)()
	int32                                         CallFunc_FTrunc_ReturnValue;                       // 0x0168(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_16C[0x4];                                      // 0x016C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select3_Default;                            // 0x0170(0x0018)()
	class UTextBlock*                             K2Node_Select4_Default;                            // 0x0188(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                K2Node_Select5_Default;                            // 0x0190(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortShowdownPinState                         CallFunc_GetEventPinState_ReturnValue;             // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortShowdownPinState                         CallFunc_GetTournamentBestPinState_ReturnValue;    // 0x0199(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortShowdownPinState                         K2Node_Select6_Default;                            // 0x019A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ShowdownPin_C_Refresh) == 0x000008, "Wrong alignment on ShowdownPin_C_Refresh");
static_assert(sizeof(ShowdownPin_C_Refresh) == 0x0001A0, "Wrong size on ShowdownPin_C_Refresh");
static_assert(offsetof(ShowdownPin_C_Refresh, PinState) == 0x000000, "Member 'ShowdownPin_C_Refresh::PinState' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, Temp_byte_Variable) == 0x000001, "Member 'ShowdownPin_C_Refresh::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, Temp_int_Variable) == 0x000004, "Member 'ShowdownPin_C_Refresh::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, Temp_int_Variable1) == 0x000008, "Member 'ShowdownPin_C_Refresh::Temp_int_Variable1' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, Temp_int_Variable2) == 0x00000C, "Member 'ShowdownPin_C_Refresh::Temp_int_Variable2' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, Temp_int_Variable3) == 0x000010, "Member 'ShowdownPin_C_Refresh::Temp_int_Variable3' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, Temp_int_Variable4) == 0x000014, "Member 'ShowdownPin_C_Refresh::Temp_int_Variable4' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, Temp_int_Variable5) == 0x000018, "Member 'ShowdownPin_C_Refresh::Temp_int_Variable5' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, Temp_int_Variable6) == 0x00001C, "Member 'ShowdownPin_C_Refresh::Temp_int_Variable6' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, Temp_byte_Variable1) == 0x000020, "Member 'ShowdownPin_C_Refresh::Temp_byte_Variable1' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, Temp_text_Variable) == 0x000028, "Member 'ShowdownPin_C_Refresh::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, Temp_text_Variable1) == 0x000040, "Member 'ShowdownPin_C_Refresh::Temp_text_Variable1' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, Temp_text_Variable2) == 0x000058, "Member 'ShowdownPin_C_Refresh::Temp_text_Variable2' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, Temp_text_Variable3) == 0x000070, "Member 'ShowdownPin_C_Refresh::Temp_text_Variable3' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, Temp_text_Variable4) == 0x000088, "Member 'ShowdownPin_C_Refresh::Temp_text_Variable4' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, Temp_text_Variable5) == 0x0000A0, "Member 'ShowdownPin_C_Refresh::Temp_text_Variable5' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, Temp_text_Variable6) == 0x0000B8, "Member 'ShowdownPin_C_Refresh::Temp_text_Variable6' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, Temp_bool_Variable) == 0x0000D0, "Member 'ShowdownPin_C_Refresh::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, Temp_bool_Variable1) == 0x0000D1, "Member 'ShowdownPin_C_Refresh::Temp_bool_Variable1' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, Temp_byte_Variable2) == 0x0000D2, "Member 'ShowdownPin_C_Refresh::Temp_byte_Variable2' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, Temp_bool_Variable2) == 0x0000D3, "Member 'ShowdownPin_C_Refresh::Temp_bool_Variable2' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, Temp_byte_Variable3) == 0x0000D4, "Member 'ShowdownPin_C_Refresh::Temp_byte_Variable3' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, CallFunc_GetBestEventScore_ReturnValue) == 0x0000D8, "Member 'ShowdownPin_C_Refresh::CallFunc_GetBestEventScore_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, CallFunc_GetCurrentEventScore_ReturnValue) == 0x0000DC, "Member 'ShowdownPin_C_Refresh::CallFunc_GetCurrentEventScore_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, CallFunc_GetEventState_ReturnValue) == 0x0000E0, "Member 'ShowdownPin_C_Refresh::CallFunc_GetEventState_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, CallFunc_GetEventState_ReturnValue1) == 0x0000E1, "Member 'ShowdownPin_C_Refresh::CallFunc_GetEventState_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, K2Node_Select_Default) == 0x0000E4, "Member 'ShowdownPin_C_Refresh::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, CallFunc_GetBestEventScore_ReturnValue1) == 0x0000E8, "Member 'ShowdownPin_C_Refresh::CallFunc_GetBestEventScore_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, CallFunc_Conv_IntToFloat_ReturnValue) == 0x0000EC, "Member 'ShowdownPin_C_Refresh::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, CallFunc_Conv_IntToText_ReturnValue) == 0x0000F0, "Member 'ShowdownPin_C_Refresh::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, CallFunc_GetCurrentEventScore_ReturnValue1) == 0x000108, "Member 'ShowdownPin_C_Refresh::CallFunc_GetCurrentEventScore_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, CallFunc_Conv_IntToText_ReturnValue1) == 0x000110, "Member 'ShowdownPin_C_Refresh::CallFunc_Conv_IntToText_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, K2Node_Select1_Default) == 0x000128, "Member 'ShowdownPin_C_Refresh::K2Node_Select1_Default' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, CallFunc_GetTournamentBestScore_ReturnValue) == 0x000140, "Member 'ShowdownPin_C_Refresh::CallFunc_GetTournamentBestScore_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, CallFunc_Conv_IntToFloat_ReturnValue1) == 0x000144, "Member 'ShowdownPin_C_Refresh::CallFunc_Conv_IntToFloat_ReturnValue1' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, K2Node_Select2_Default) == 0x000148, "Member 'ShowdownPin_C_Refresh::K2Node_Select2_Default' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, CallFunc_Conv_IntToText_ReturnValue2) == 0x000150, "Member 'ShowdownPin_C_Refresh::CallFunc_Conv_IntToText_ReturnValue2' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, CallFunc_FTrunc_ReturnValue) == 0x000168, "Member 'ShowdownPin_C_Refresh::CallFunc_FTrunc_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, K2Node_Select3_Default) == 0x000170, "Member 'ShowdownPin_C_Refresh::K2Node_Select3_Default' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, K2Node_Select4_Default) == 0x000188, "Member 'ShowdownPin_C_Refresh::K2Node_Select4_Default' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, K2Node_Select5_Default) == 0x000190, "Member 'ShowdownPin_C_Refresh::K2Node_Select5_Default' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, CallFunc_GetEventPinState_ReturnValue) == 0x000198, "Member 'ShowdownPin_C_Refresh::CallFunc_GetEventPinState_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, CallFunc_GetTournamentBestPinState_ReturnValue) == 0x000199, "Member 'ShowdownPin_C_Refresh::CallFunc_GetTournamentBestPinState_ReturnValue' has a wrong offset!");
static_assert(offsetof(ShowdownPin_C_Refresh, K2Node_Select6_Default) == 0x00019A, "Member 'ShowdownPin_C_Refresh::K2Node_Select6_Default' has a wrong offset!");

}

